[package]
name = "cybus"
version = "0.1.0"
authors = ["Charlie Wilkin <cwilkin@protonmail.com>"]
edition = "2018"

[dependencies]
# Logging
log = "~0"
fern = { version = "0.5", features = ["colored"] }

# Time
chrono = "~0"
