[package]
name = "cybus"
version = "0.1.0"
authors = ["Charlie Wilkin <cwilkin@protonmail.com>"]
edition = "2018"

[dependencies]
# Logging
log = { version = "~0", features = ["release_max_level_error"] }
fern = { version = "~0", features = ["colored"] }

# Time
chrono = "~0"
